#! /nix/store/czx8vkrb9jdgjyz8qfksh10vrnqa723l-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/x21z7ya4jmlf6ml72cr4izppm8cw4akb-iproute2-4.18.0/bin'${PATH:+':'}$PATH
exec -a "$0" "/nix/store/dqlbv2klygfv06hbzn0awcd7sy1rmsnv-i3blocks-1.4/libexec/i3blocks/.bandwidth-wrapped"  "${extraFlagsArray[@]}" "$@"
