#! /nix/store/czx8vkrb9jdgjyz8qfksh10vrnqa723l-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/kh5i6qzpphnfbnzd5h5yby9jbib20h6g-acpi-1.7/bin'${PATH:+':'}$PATH
exec -a "$0" "/nix/store/dqlbv2klygfv06hbzn0awcd7sy1rmsnv-i3blocks-1.4/libexec/i3blocks/.battery-wrapped"  "${extraFlagsArray[@]}" "$@"
