#! /nix/store/czx8vkrb9jdgjyz8qfksh10vrnqa723l-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/n1czwv15qqxhlavp9lcf6xrg3wwwk9wv-sysstat-12.0.1/bin'${PATH:+':'}$PATH
exec -a "$0" "/nix/store/dqlbv2klygfv06hbzn0awcd7sy1rmsnv-i3blocks-1.4/libexec/i3blocks/.cpu_usage-wrapped"  "${extraFlagsArray[@]}" "$@"
