#! /nix/store/czx8vkrb9jdgjyz8qfksh10vrnqa723l-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/kb7mmbm41m001lk9x7x6r3arnxixb1jm-xset-1.2.3/bin'${PATH:+':'}$PATH
exec -a "$0" "/nix/store/dqlbv2klygfv06hbzn0awcd7sy1rmsnv-i3blocks-1.4/libexec/i3blocks/.keyindicator-wrapped"  "${extraFlagsArray[@]}" "$@"
