#! /nix/store/czx8vkrb9jdgjyz8qfksh10vrnqa723l-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/856rx0c25g5nr3d6f942is9wnvrziq38-playerctl-0.6.1/bin:/nix/store/ifkpphd4b4whcdcxl87v2y2pk86nh77k-cmus-2.7.1/bin'${PATH:+':'}$PATH
exec -a "$0" "/nix/store/dqlbv2klygfv06hbzn0awcd7sy1rmsnv-i3blocks-1.4/libexec/i3blocks/.mediaplayer-wrapped"  "${extraFlagsArray[@]}" "$@"
