#! /nix/store/czx8vkrb9jdgjyz8qfksh10vrnqa723l-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/iybgwyvbjwnia6smm87pa9982lv8ps1p-openvpn-2.4.6/bin'${PATH:+':'}$PATH
exec -a "$0" "/nix/store/dqlbv2klygfv06hbzn0awcd7sy1rmsnv-i3blocks-1.4/libexec/i3blocks/.openvpn-wrapped"  "${extraFlagsArray[@]}" "$@"
