#! /nix/store/czx8vkrb9jdgjyz8qfksh10vrnqa723l-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/sbjg54s5dpnhv3r9xrzbf2qm50189qpm-lm-sensors-3.4.0/bin'${PATH:+':'}$PATH
exec -a "$0" "/nix/store/dqlbv2klygfv06hbzn0awcd7sy1rmsnv-i3blocks-1.4/libexec/i3blocks/.temperature-wrapped"  "${extraFlagsArray[@]}" "$@"
