#! /nix/store/czx8vkrb9jdgjyz8qfksh10vrnqa723l-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/fjq2d4p2szs5v8ll000kz5cl8k1yxxdw-alsa-utils-1.1.6/bin'${PATH:+':'}$PATH
exec -a "$0" "/nix/store/dqlbv2klygfv06hbzn0awcd7sy1rmsnv-i3blocks-1.4/libexec/i3blocks/.volume-wrapped"  "${extraFlagsArray[@]}" "$@"
